import type { DataHandlerContext } from "@subsquid/substrate-processor";
import type { Store } from "@subsquid/typeorm-store";
import type { Ss58Codec } from "./codec";
import type { BlockHeight } from "./primitives";

/**
 * Minimum contract a squid's `Account` model class must satisfy for the
 * shared cache helper. Each squid defines its own concrete entity (with its
 * own relations) but the construction/upsert shape is the same.
 */
export interface AccountLike {
	id: string;
	firstSeenAtBlock: bigint;
	lastSeenAtBlock: bigint;
}

/**
 * Account-construction props the helper passes to `make`. Squid Account
 * classes generated by `squid-typeorm-codegen` accept `Partial<A>`, so the
 * caller's `make` is usually just `(p) => new Account(p)`.
 */
export interface AccountProps {
	id: string;
	firstSeenAtBlock: bigint;
	lastSeenAtBlock: bigint;
}

/**
 * Caller-supplied entity binding. `target` is the TypeORM entity reference
 * `store.get` / `store.upsert` consume; `make` is a small factory that
 * produces a fresh instance from the shared `AccountProps` shape. Splitting
 * `make` from `target` sidesteps Subsquid's `EntityClass<T>` constraint that
 * requires a zero-argument constructor (which the typegen-generated classes
 * don't have).
 */
export interface AccountEntity<A extends AccountLike> {
	/** TypeORM entity reference. The typegen-generated Account class fits because
	 * its constructor parameter is optional, so it satisfies `new () => A`. */
	target: new () => A;
	make(props: AccountProps): A;
}

type AccountCtx = Pick<DataHandlerContext<Store, any>, "store">;

/**
 * Factory for the per-batch account-upsert helpers. Each squid calls this
 * once at module load with its own concrete Account binding and SS58 codec;
 * the returned `getOrCreateAccount` and `getOrCreateAccountFromBytes` are the
 * actual helpers handlers consume.
 *
 * The factory pattern decouples the shared logic (cache, upsert, first/last-
 * seen advancement) from the squid-specific Account class without resorting
 * to runtime entity-class lookups.
 */
export function createAccountHelpers<A extends AccountLike>(opts: {
	account: AccountEntity<A>;
	codec: Ss58Codec;
}) {
	const { account, codec } = opts;

	/**
	 * Per-batch cache keyed by ctx (lifetime = batch). Avoids duplicate
	 * `store.get(Account, id)` round-trips when the same address appears in
	 * many events of the same batch. GC'd when the batch completes.
	 */
	const CACHE = new WeakMap<object, Map<string, A>>();

	function cacheFor(ctx: AccountCtx): Map<string, A> {
		let c = CACHE.get(ctx);
		if (!c) {
			c = new Map();
			CACHE.set(ctx, c);
		}
		return c;
	}

	async function getOrCreateAccount(
		ctx: AccountCtx,
		id: string,
		blockNumber: BlockHeight,
	): Promise<A> {
		const cache = cacheFor(ctx);

		let acc = cache.get(id);
		if (!acc) {
			acc =
				(await ctx.store.get(account.target, id)) ??
				account.make({
					id,
					firstSeenAtBlock: blockNumber,
					lastSeenAtBlock: blockNumber,
				});
			cache.set(id, acc);
		}

		if (blockNumber > acc.lastSeenAtBlock) {
			acc.lastSeenAtBlock = blockNumber;
		}

		await ctx.store.upsert(acc);
		return acc;
	}

	function getOrCreateAccountFromBytes(
		ctx: AccountCtx,
		rawBytes: Uint8Array,
		blockNumber: BlockHeight,
	): Promise<A> {
		return getOrCreateAccount(ctx, codec.encodeAddress(rawBytes), blockNumber);
	}

	return { getOrCreateAccount, getOrCreateAccountFromBytes } as const;
}
